### ISSUE TITLE
value too great for base (error token is "1485458095N")

### ISSUE THREAD

**Issue by purplejacket** [thelazt/chessbash#2]
I get an error trying to run this in recent OSX.  It worked for me when I tried it about a year ago.  It does work in Ubuntu though.

$ uname -a
Darwin aerolith.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

$ ./chessba.sh
͏\e[6n./chessba.sh: line 67: read: -N: invalid option
read: usage: read [-ers] [-u fd] [-t timeout] [-p prompt] [-a array] [-n nchars] [-d delim] [name ...]
\e[0me8\e[2K
Welcome to \e[1mChessBa.sh\e[0m - a Chess game written in Bash \e[2mby Bernhard Heinloth, 2015\e[0m

\e[18t\e7\e[s\e[?47h\e[?25l\e[2J\e[H
./chessba.sh: line 627: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
./chessba.sh: line 628: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
./chessba.sh: line 629: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
./chessba.sh: line 632: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
./chessba.sh: line 636: redraw[$y,$x]: bad array subscript
./chessba.sh: line 638: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
./chessba.sh: line 187: ${namePlayerB,,}: bad substitution
./chessba.sh: line 187: ${namePlayerB,,}: bad substitution
\e[H\e[?25l\e[0m
\e[KGame Over!\e[0m
\e[K
./chessba.sh: line 1283: redraw: bad array subscript
\e[0m\e[4;3H H\e[0m\e[8m./chessba.sh: line 1285: redraw[$ty,$tx]: bad array subscript
\e[?9l\e[2J\e[?47l\e[?25h\e[u\e8./chessba.sh: line 1693: 1485458095N: value too great for base (error token is "1485458095N")

**Comment by IgorLeMasson** [comment]
Hi @purplejacket,

It was fixed, basically, the BASH version 4 is required. You can find tutorials about how to update BASH in the OSX.
