### ISSUE TITLE
Rows and columns are backwards, king and queen are reversed.

### ISSUE THREAD

**Issue by purplejacket** [thelazt/chessbash#3]
The letters a-h should be along the bottom and the numbers 1-8 go vertically.  The way it's currently coded is extremely confusing to a normal chess player.  Also, if the Player is white (blue pieces), then her King and Queen should be swapped.  So in the end, the move e2-e4 would move the King's pawn from the second row to the fourth row.  The computer might respond with e7-e5, mirroring the Player's strategy.  The player might bring the King's Knight out with g1-f3 attacking the computer's pawn on e5, etc.

**Comment by IgorLeMasson** [comment]
Hi @purplejacket,

Thanks for reporting it, this issue was fixed. :)
