### ISSUE TITLE
Unicode pieces

### ISSUE THREAD

**Issue by eugrus** [thelazt/chessbash#6]
Great work!

It would be also fun to have a version with Unicode symbols for chess pieces (U+1FA00..U+1FA6F) instead of the ASCII representation.

**Comment by thelazt** [comment]
Unicode symbols for chess pieces are [already supported](https://github.com/thelazt/chessbash/blob/master/chessba.sh#L1288) (using the basic symbols [U+2654..U+265F](https://www.unicode.org/charts/PDF/U2600.pdf) -- I don't see the advantage in using the [fairy chess pieces](https://en.wikipedia.org/wiki/Chess_symbols_in_Unicode#Fairy_chess_pieces)).

Perhaps your terminal emulator might have issues to display them correctly?
There is [some code to check if Unicode is supported](https://github.com/thelazt/chessbash/blob/master/chessba.sh#L75), but it may happen that it fails on some terminal emulator.
You could test this by just adding a line `ascii=false` somewhere after the check/assignment, e.g. in line 632.

**Comment by eugrus** [comment]
Velen Dank für die schnelle Antwort! Werde nun schauen, woran es bei mir liegt :)
